### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by bluesource** [seatsurfing/backend#106]
Upgrade from 1.11.3 to 1.12.x fails with following error:

```
server_1  | panic: pq: column "disabled" of relation "users" already exists
server_1  |
server_1  | goroutine 1 [running]:
server_1  | main.(*UserRepository).RunSchemaUpgrade(0x806ae8?, 0xd, 0xc00021fe18?)
server_1  |     /go/src/app/server/user-repository.go:109 +0x385
server_1  | main.RunDBSchemaUpdates()
server_1  |     /go/src/app/server/db-updates.go:34 +0x34d
server_1  | main.(*App).InitializeDatabases(0xc00021ff60?)
server_1  |     /go/src/app/server/app.go:33 +0x17
server_1  | main.main()
server_1  |     /go/src/app/server/main.go:29 +0xaf
```
Database Error log:
```
db_1      | 2023-02-20 09:24:18.959 UTC [44] ERROR:  column "disabled" of relation "users" already exists
db_1      | 2023-02-20 09:24:18.959 UTC [44] STATEMENT:  ALTER TABLE users ADD COLUMN disabled boolean NOT NULL DEFAULT FALSE, ADD COLUMN ban_expiry TIMESTAMP NULL DEFAULT NULL
```

regards,
Michael

**Comment by virtualzone** [comment]
Hi @bluesource , 

I can't reproduce this issue with a clean instance at version 1.11.3 which is updated to 1.12.2. I guess the database schema version is not recorded correctly for some reason while the schema already got upgraded.

You can query the current schema version by running the following command (assuming you're using Docker Compose with the example YAML from the Readme):
```
docker compose exec db psql -d seatsurfing -U seatsurfing -c "select value from settings where name = 'db_version';"
```

If the resulting value is ```13```, please try to set it to 14 by running the following command:
```
docker compose exec db psql -d seatsurfing -U seatsurfing -c "update settings set value = '14' where name = 'db_version';"
```

Then try to start the Seatsurfing backend again.

**Comment by fashberg** [comment]
worked like a charm for me (tm)

```2023/02/21 17:03:58 Starting...
2023/02/21 17:03:58 Seatsurfing Backend Version 1.12.2
2023/02/21 17:03:58 Connecting to database...
2023/02/21 17:03:58 Reading config...
2023/02/21 17:03:58 Database connection established.
2023/02/21 17:03:58 Initializing database with schema version 14...
2023/02/21 17:03:58 Configuring default settings for orgs...
2023/02/21 17:03:58 Configuring default preferences for users...
2023/02/21 17:03:58 Initializing REST services...
2023/02/21 17:03:58 HTTP Server listening on 0.0.0.0:8080
2023/02/21 17:04:58 Cleaning up expired database entries...
```

**Comment by bluesource** [comment]
Thank you this fixes the problem
